### PR TITLE
Incorporate Saturn with custom keywords

### PR DESCRIPTION
**Pull request by isaacabraham**
@Krzysztof-Cieslak as we discussed yesterday, here's a really quick version of how something like this *could* look using Saturn - I've kind of taken it "to the max" by adding in a few custom operators in the `application { }` block.

There's actually no "code saving" in code-golf terms, but I think the separation between service, host and endpoint configuration is quite nice.

Note also the fact that I had to create a "dummy" route to "get around" the need to create that in Saturn (I've created https://github.com/SaturnFramework/Saturn/issues/191 as a result).

### CODE REVIEW

**Comment by isaacabraham** [comment]
Also cc @mgravell - Saturn is a lightweight "wrapper" on top of ASP .NET Core that takes advantage of some F# features to allow a more declarative way to create and configure ASP .NET Core applications. This is more of a prototype that will help us look at adding some features to Saturn to make it more friendly to non-"standard" (i.e. web api / mvc) style applications.

**Comment by Krzysztof-Cieslak** [comment]
Can we go even further with that?

As far as I can tell those are crucial, GRPC specific parts (`use_http2` and `use_developer_exceptions` makes sense for core Saturn, we should add them):

```
let configureServices (services: IServiceCollection) =
    services.AddCodeFirstGrpc()
    services

let configureEndpoints (endpoints:Routing.IEndpointRouteBuilder) =
    endpoints.MapGrpcService<MyCalculator>()

...

application {
  use_routing
  service_config configureServices
  endpoint_config configureEndpoints
  ...
}
```

It seems for me it's still focused on implementation details - enabling routing, configuring endpoints manually. What I'd want is `use_grpc_service<'a>` that would do all this for me. 
Also, at least for now, I don't want to leak Endpoint Routing to the users - we do have one way of defining routing in our applications (`use_route` + Giraffe) and I don't want to introduce another, so `use_routing` and `endpoint_config` shouldn't be exposed, IMO.

**Comment by isaacabraham** [comment]
Yep, that could definitely make sense - i wasn't really sure at what level the abstraction layer should be. I don't know if endpoint configures and UseRouting() are really generic / reusable abstractions or not. If not, then yes, something like "use_gprc" makes sense. You know better than me here :-)

* `use_http2` - I have no clue how that composes with other parts of aspnetcore - I think some more investigation might be needed there.
* `use_developer_exceptions` - yes that seems pretty generic and useful.

**Comment by Krzysztof-Cieslak** [comment]
> `use_http2` - I have no clue how that composes with other parts of aspnetcore - I think some more investigation might be needed there.

Scott mentions it's enabled by deafult in 2.2 - https://www.hanselman.com/blog/UsefulASPNETCore22Features.aspx

> HTTP/2 is enabled by default. HTTP/2 may be sneaking up on you as for the most part "it just works." In ASP.NET Core's Kestral web server HTTP/2 is enabled by default over HTTPS. You can see here at both the command line and in Chrome I'm using HTTP/2 locally.

**Comment by Krzysztof-Cieslak** [comment]
> I don't know if endpoint configures and UseRouting() are really generic / reusable abstractions or not

I mean, they're reusable abstractions, but I don't think they're abstractions we need ;-)

**Comment by isaacabraham** [comment]
> Scott mentions it's enabled by deafult in 2.2 - https://www.hanselman.com/blog/UsefulASPNETCore22Features.aspx

Does that mean that entire element can be removed from this sample I wonder.

**Comment by isaacabraham** [comment]
Also note that we couldn't directly add the GRPC methods (`MapGrpcService` and `AddCodeFirstGrpc`) without taking a dependency on this library directly. I'm not sure that's a good idea to add directly to Saturn.

**Comment by Krzysztof-Cieslak** [comment]
> `use_http2`

After looking at it for a while at `use_http2` - I think the main thing is actually `ListenLocal` method, not setting protocol.  (https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserveroptions.listenlocalhost?view=aspnetcore-2.2). As far as I understand, it makes kestrel listen to communication on given port (normally in Saturn that's handled by [internal `UseUrls` call](https://github.com/SaturnFramework/Saturn/blob/master/src/Saturn/Application.fs#L111) ). So it probably shouldn't be called `use_http2` but rather `listen_local` (and take port and ListenOptions as an input)

> Also note that we couldn't directly add the GRPC methods (MapGrpcService and AddCodeFirstGrpc) without taking a dependency on this library directly. I'm not sure that's a good idea to add directly to Saturn.

I think we can do as Saturn extension package (we do that already for some specific stuff, for example HttpSys integration - https://github.com/SaturnFramework/Saturn/tree/master/src/Saturn.Extensions.HttpSys)

**Pull request closed without merging**
